/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  
  generalSidebar: [
    {
      type: 'category',
      label: 'Getting started',
      link: {type: 'doc', id: 'README'},
      items: [
        {
          type: 'doc',
          id: 'general/table-content',
          label: '🌿 Table of Content',
        },
        {
          type: 'category',
          label: '💡 Concepts',
          items: [
            {
              type: 'autogenerated',
              dirName: 'general/high-level', // Generate sidebar slice from docs/high-level
            },
          ]
        },     
        {
          type: 'doc',
          id: 'general/FAQ/README',
          label: '❓ FAQ',
        },
        {
          type: 'doc',
          id: 'general/audits',
          label: '🔍 Audits',
        },  
        {
          type: 'category',
          label: '💻 App guide',
          items: [
            {
              type: 'autogenerated',
              dirName: 'general/web-app',
            },
          ]
        },
      ],
    },
  {
    type: 'category',
    label: 'Strategies',
    collapsed: false,
    items: [
      {
        type: 'category',
        label: '♟️ Kandel',
        collapsed: false,
        items: [
          {
            type: 'autogenerated',
            dirName: 'general/kandel', // Generate sidebar slice from docs/high-level
          },
        ]
      },
    ],
  },
  {
    type: 'category',
    label: 'Quick links',
    collapsed: false,
    items: [
      {
        type: 'link',
        label: '📃 Whitepaper', // The link label
        href: 'https://bafybeig62o75bfxssic66w2zwerbo6ezlhb33vsg5idr4uprckn2dxrucy.ipfs.dweb.link/',
      },
      {
        type: 'link',
        label: '🕸️ Website', // The link label
        href: 'https://mangrove.exchange/',
      },
      {
        type: 'link',
        label: '💬 Feedback', // The link label
        href: 'https://tally.so/r/w54D5Q',
      },
      {
        type: 'link',
        href: '/developers/glossary',
        label: '🔤 Glossary',
      },
      {
        type: 'link',
        href: '/developers/',
        label: '🏗️ Developers',
      },
    ],
  },
  {
    type: 'category',
    label: 'Socials',
    collapsed: false,
    items: [
      {
        type: 'link',
        label: '📰 Blog', // The link label
        href: 'https://blog.mangrove.exchange/',
      },
      {
        type: 'link',
        label: '👾 Discord', // The link label
        href: 'https://discord.gg/rk9Qthz5YE',
      },
      {
        type: 'link',
        label: '🐦 X', // The link label
        href: 'https://twitter.com/MangroveDAO',
      },
      {
        type: 'link',
        label: '🧩 GitHub', // The link label
        href: 'https://github.com/mangrovedao',
      },
      {
        type: 'link',
        label: '🎨 Assets', // The link label
        href: 'https://www.mangrove.exchange/brand-assets',
      },
      {
        type: 'link',
        label: '📝 Contact', // The link label
        href: 'https://docs.google.com/forms/d/e/1FAIpQLSewVLx1AcOwK0DOvMOCIb7hSEfHGwMzB0P4yeH-Aeq65ctlKg/viewform',
      },
    ],
  },
  ],

  developerSidebar: [
    {
      type: 'doc',
      id: 'developers/README',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Contracts',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'developers/contracts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Strat Lib',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'developers/strat-lib',
        },
      ],
    },
    {
      type: 'category',
      label: 'SDK',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'developers/SDK',
        },
      ],
    },
    {
      type: 'category',
      label: 'Keeper Bots',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'developers/keeper-bots',
        },
      ],
    },
    {
      type: 'category',
      label: 'Quick links',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'developers/contracts/technical-references/contract-addresses',
          label: '🚁 Deployment addresses',
        },
        {
          type: 'doc',
          id: 'developers/glossary',
          label: '🔤 Glossary',
        },
        {
          type: 'link',
          label: '📃 Whitepaper', // The link label
          href: 'https://bafybeig62o75bfxssic66w2zwerbo6ezlhb33vsg5idr4uprckn2dxrucy.ipfs.dweb.link/',
        },
        {
          type: 'link',
          label: '🕸️ Website', // The link label
          href: 'https://mangrove.exchange/',
        },
      ],
    },
  ],
  
  termSidebar: [
    'developers/glossary',
    {
      type: 'autogenerated', 
      dirName: 'developers/terms'
    },
  ],
};

module.exports = sidebars;
