/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  
  docsSidebar: [
  
    {
      type: 'category',
      label: 'Concepts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'high-level', // Generate sidebar slice from docs/high-level
        },
      ],
    },
    {
      type: 'category',
      label: 'Web App',
      items: [
        {
          type: 'autogenerated',
          dirName: 'web-app',
        },
      ],
    },
    {
      type: 'category',
      label: 'Kandel',
      items: [
        {
          type: 'autogenerated',
          dirName: 'kandel',
        },
      ],
    },
    {
      type: 'category',
      label: 'Contracts',
      items: [
        {
          type: 'autogenerated',
          dirName: 'contracts',
        },
      ],
    },
    {
      type: 'category',
      label: 'Strat Lib',
      items: [
        {
          type: 'autogenerated',
          dirName: 'strat-lib',
        },
      ],
    },
    {
      type: 'category',
      label: 'SDK',
      items: [
        {
          type: 'autogenerated',
          dirName: 'SDK',
        },
      ],
    },
    {
      type: 'category',
      label: 'Keeper Bots',
      items: [
        {
          type: 'autogenerated',
          dirName: 'keeper-bots',
        },
      ],
    },
    {
      type: 'category',
      label: 'Glossary',
      items: [
        {
          type: 'autogenerated',
          dirName: 'terms',
        },
      ],
    },
  ],
};

module.exports = sidebars;
