/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  coreSidebar: [ {
    type: 'autogenerated', 
    dirName: 'mangrove-core'
  },
],
  sdkSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'mangrove-js'
    },
  ],
  botsSidebar: [
    'glossary',
    {
      type: 'autogenerated', 
      dirName: 'keeper-bots'
    },
  ],
  termSidebar: [
    'glossary',
    {
      type: 'autogenerated', 
      dirName: 'terms'
    },
  ],
};

module.exports = sidebars;
